project:
  type: website

website:
  title: "Puri Phakmongkol"
  site-url: "https://www.puri.in.th"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  search:
    location: sidebar
    type: overlay

format:
  html:
    page-layout: full
    date-format: "MMM YYYY"
    theme:
      light:
        - flatly
        - mozilla.scss
    css: styles.css
    toc: false

execute: 
  freeze: auto


